import html from '../presentation/assets/logo/html.svg';
import css from '../presentation/assets/logo/css.svg';
import JS from '../presentation/assets/logo/javascript.svg';
import TS from '../presentation/assets/logo/typescript.svg';
import sass from '../presentation/assets/logo/sass.svg';
import styled_component from '../presentation/assets/logo/styled-component.svg';
import bootstrap from '../presentation/assets/logo/bootstrap.svg';
import tailwind from '../presentation/assets/logo/tailwindcss.svg';
import materialUi from '../presentation/assets/logo/material-ui.svg';
import react from '../presentation/assets/logo/react.svg';
import redux from '../presentation/assets/logo/redux.svg';
import zustand from '../presentation/assets/logo/zustand.svg';
import next from '../presentation/assets/logo/nextjs.svg';
import nodejs from '../presentation/assets/logo/nodejs.svg';
import express from '../presentation/assets/logo/express.svg';
import nestjs from '../presentation/assets/logo/nestjs.svg';
import python from '../presentation/assets/logo/python.svg';
import django from '../presentation/assets/logo/django.svg';
import fastApi from '../presentation/assets/logo/fastapi.svg';
import postgresql from '../presentation/assets/logo/postgresql.svg';
import mysql from '../presentation/assets/logo/mysql.svg';
import mongodb from '../presentation/assets/logo/mongo.svg';
import redis from '../presentation/assets/logo/redis.svg';
import sequelize from '../presentation/assets/logo/sequelize.svg';
import mongoose from '../presentation/assets/logo/mongoose.svg';
import aws from '../presentation/assets/logo/aws.svg';
import lambda from '../presentation/assets/logo/aws-lambda.svg';
import awsApiGateway from '../presentation/assets/logo/aws-api-gateway.svg';
import awsCloudWatch from '../presentation/assets/logo/aws-cloudwatch.svg';
import git from '../presentation/assets/logo/git.svg';
import github from '../presentation/assets/logo/github.svg';
import jest from '../presentation/assets/logo/jest.svg';
import cypress from '../presentation/assets/logo/cypress.svg';
import docker from '../presentation/assets/logo/docker.svg';
import AWS_S3 from '../presentation/assets/logo/aws-s3.svg';
import cognito from '../presentation/assets/logo/aws-cognito.svg';
import serverless_framework from '../presentation/assets/logo/serverless-framework.svg';
import send_message from '../presentation/assets/logo/send-message.png';

export const HTML = html;
export const CSS = css;
export const Javascript = JS;
export const Typescript = TS;
export const SASS = sass;
export const Styled_Component = styled_component;
export const Bootstrap = bootstrap;
export const TailwindCSS = tailwind;
export const MaterialUI = materialUi;
export const React = react;
export const Redux = redux;
export const Zustand = zustand;
export const NextJS = next;
export const NodeJS = nodejs;
export const Express = express;
export const NestJS = nestjs;
export const Python = python;
export const Django = django;
export const FastAPI = fastApi;
export const Postgresql = postgresql;
export const Mysql = mysql;
export const Mongodb = mongodb;
export const Redis = redis;
export const Sequelize = sequelize;
export const Mongoose = mongoose;
export const AWS = aws;
export const AWSLambda = lambda;
export const AWSApiGateway = awsApiGateway;
export const AWSCloudWatch = awsCloudWatch;
export const Git = git;
export const GitHub = github;
export const Jest = jest;
export const Cypress = cypress;
export const Docker = docker;
export const S3 = AWS_S3;
export const Cognito = cognito;
export const ServerlessFramework = serverless_framework;
export const SendMessage = send_message;
